# Generated by Django 4.2 on 2023-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_projectcybrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCybrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('quality', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='About_image')),
            ],
        ),
    ]
