# Generated by Django 4.2 on 2023-06-19 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('full_desc', models.FloatField()),
                ('fees', models.FloatField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.servicecybrom')),
            ],
        ),
    ]
