# Generated by Django 4.2 on 2023-06-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_sectionsix_alter_servicerelated_full_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('fees', models.BigIntegerField()),
                ('query', models.TextField()),
            ],
        ),
    ]
